# Generated by Django 3.1.5 on 2021-01-28 15:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210128_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='uploads/'),
        ),
    ]
