# Generated by Django 3.1.5 on 2021-01-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
