# Generated by Django 3.1.5 on 2021-01-29 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragragh_one', models.TextField(blank=True, null=True)),
                ('paragragh_two', models.TextField(blank=True, null=True)),
                ('paragragh_three', models.TextField(blank=True, null=True)),
                ('paragragh_four', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
