# Generated by Django 3.1.5 on 2021-01-29 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='paragragh_four',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragragh_one',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragragh_three',
        ),
        migrations.RemoveField(
            model_name='about',
            name='paragragh_two',
        ),
    ]
